name: runner group

on:
  push:
    branches:
      - dev

concurrency:
  group: build and test
  # cancel-in-progress: true


jobs:
  check-bats-version:
    runs-on: ubuntu-latest
      # group: ubuntu-runners
      # labels: ubuntu-20.04-16core
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install -g bats
      - run: bats -v 
      
    
