name: matrix jobs

on: 
  push:
    branches:
      - main

jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [10,11,12]
        # os: [ubuntu-latest, windows-latest]
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
