name: matrix jobs

on: 
  push:
    branches:
      - main

jobs:
  example_matrix:
    strategy:
      matrix:
        version: [10,11,12]
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            # version: [13,14]
            version: 13
        exclude:
          - os: windows-latest
            version: 12
        # os: [ubuntu-latest, windows-latest]
    runs-on: ubuntu-latest
    # runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
