name: default

on:
  push:
    branches:
      - dev

# defaults:
#       run: 
#         shell: bash
#         working-directory: scripts

jobs:
  default_jobs:
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash
        # working-directory: scripts
    steps:
      - name: print Hello World
        run: echo "Hello World"
    