name: permissions

on:
  push:
    branches:
      - main

# permissions: read-all 

jobs:
  permissions_job:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: print hello World
        run: echo "Hello World"


      
    