name: output

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}

    steps:
      - name: step1
        id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - name: step2
        id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT
  job2:
    # runs-on: ubuntu-latest
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - env:
          OUTPUT1: ${{ needs.job1.outputs.output1 }}
          OUTPUT2: ${{ needs.job1.outputs.output2 }}
        run: echo "$OUTPUT1 $OUTPUT2"



